### ISSUE TITLE
Compile error on linux

### ISSUE THREAD

**Issue by danknights** [GabeAl/NINJA-SHI7#3]
In file included from ninja_shi7.c:2:0:
/soft/gcc-4.5.2/ubuntuamd1/lib/gcc/x86_64-unknown-linux-gnu/4.5.2/include/smmintrin.h:32:3: error: #error "SSE4.1 instruction set not enabled"

Solved with 
gcc -m64 -O3 -std=gnu99 -msse4.1 -fwhole-program ninja_shi7.c -o ninja_shi7

**Comment by GabeAl** [comment]
Thanks. I'd left an extra line in. Actually doesn't need SSE4. The benefits of copy-pasta (I always compile with -march=native which automatically activates everything my processor has, so I never noticed!)
